language = "zh"
data_dir = "/root/.cc-connect/data"

[log]
level = "info"

[[projects]]
name = "c-nexus"
admin_from = "YOUR_WECHAT_ACCOUNT_1"

[projects.agent]
type = "claudecode"

[projects.agent.options]
work_dir = "/root/projects/c-nexus"
mode = "default"

[projects.agent.options.env]
ANTHROPIC_AUTH_TOKEN = "YOUR_ANTHROPIC_TOKEN"
ANTHROPIC_BASE_URL = "https://api.deepseek.com/anthropic"
ANTHROPIC_DEFAULT_HAIKU_MODEL = "deepseek-v4-flash"
ANTHROPIC_DEFAULT_OPUS_MODEL = "deepseek-v4-pro"
ANTHROPIC_DEFAULT_OPUS_MODEL_NAME = "deepseek-v4-pro"
ANTHROPIC_DEFAULT_SONNET_MODEL = "deepseek-v4-pro[1M]"
ANTHROPIC_DEFAULT_SONNET_MODEL_NAME = "deepseek-v4-pro"
ANTHROPIC_MODEL = "deepseek-v4-pro"

[[projects.platforms]]
type = "weixin"

[projects.platforms.options]
token = "YOUR_BOT_TOKEN_1"
base_url = "https://ilinkai.weixin.qq.com"
account_id = "e9920527c824@im.bot"
allow_from = "YOUR_WECHAT_ACCOUNT_1"

[[projects.platforms]]
type = "weixin"

[projects.platforms.options]
token = "YOUR_BOT_TOKEN_2"
base_url = "https://ilinkai.weixin.qq.com"
account_id = "8adcca8dc931@im.bot"
allow_from = "YOUR_WECHAT_ACCOUNT_2"
